[package]
name = "kdctl-host"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"

[build-dependencies]
winres = "0.1.12"

[dependencies]
log = "0.4.18"
flexi_logger = { version = "0.31.9", features = [] }
ntapi = "0.4.3"
anyhow = "1.0.75"
winapi = "0.3.9"
pnet = "*"
windows-service = "0.8.1"
winlog = "*"
kdctl-server = { path = "../server" }
kdctl-shared = { path = "../shared" }

[dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_WindowsProgramming",
    "Win32_System_Memory",
    "Win32_System_ProcessStatus",
    "Win32_System_Diagnostics",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Services",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Kernel",
    "Win32_UI_Shell",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Registry",
    "Win32_Foundation",
    "Win32_System_Console",
    "Wdk_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_System_Pipes"
]
# blowfish = "0.9.1"
# aes = "0.8.4"
# md5 = "0.8.0"
# flate2 = "1.1.9"
# zstd = "0.13.3"
# async-compression = { version = "0.4.41", features = ["tokio", "gzip", "zstd"] }

# byteorder = "1.5.0"
# tokio-util = { version = "0.7.18", features = ["io", "compat"] }
# tokio = { version = "1.51.0", features = ["time", "fs", "io-util"] }
# block-modes = "0.9.1"
# sha2 = "0.11.0"
# hex-literal = "1.0.0"
# cipher = "0.4.4"
# ecb = "0.1.2"
# hex = "0.4.3"
# chrono = { version = "0.4.31", features = ["serde"] }
# rand = "0.9.0"
# encoding_rs = "0.8.35"
# regex = "1.11.2"
# glob = "0.3.3"
